branch-defaults:
  awsBranch:
    environment: null
    group_suffix: null 
global:
  application_name: todo-react-app
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: build/libs/demo-0.0.1-SNAPSHOT.jar